### ISSUE TITLE
Rendered whitespace inhibits legibility

### ISSUE THREAD

**Issue by le717** [firefox-theme/visual-studio-code#1]
As can be seen in the screenshots. :)

Dark:
![image](https://cloud.githubusercontent.com/assets/3382464/24733092/7572232c-1a43-11e7-8967-e0f844f6768a.png)

Darker:
![image](https://cloud.githubusercontent.com/assets/3382464/24733105/84163efe-1a43-11e7-877a-63df9cb4bf7d.png)

**Comment by eronh** [comment]
Hi, Caleb o/
Thanks for the feedback.
I will work on this issue and release an update as soon as possible.
