### ISSUE TITLE
Dark Theme makes the menu bar text invisible when using custom title bar style

### ISSUE THREAD

**Issue by ExE-Boss** [firefox-theme/visual-studio-code#12]
## STR:
1. Have VSCode 1.26
2. [Set `window.titleBarStyle` to `custom` in `settings.json`.](https://code.visualstudio.com/updates/v1_26#_custom-title-bar-and-menus-for-windowslinux)
3. Restart VSCode.
4. Enable the “Firefox Dark” theme.
5. The menu bar text is invisible.

**Comment by eronh** [comment]
Hi @ExE-Boss 
Thank you for reporting this issue.

I shall publish a new patch until tomorrow.
