### ISSUE TITLE
Light theme: Peak definition style broken

### ISSUE THREAD

**Issue by BoruiGu** [firefox-theme/visual-studio-code#14]
as seen in the screenshot, style for peek definition window looks unfinished not readable

![image](https://user-images.githubusercontent.com/8686167/50747346-75ac3c80-1201-11e9-997b-a5a5ba6488a7.png)

**Comment by eronh** [comment]
Hi, @BoruiGu!
Thank you for reporting this, it's really messed up :man_facepalming: 

I haven't had any time to work on the theme recently, but have already established a milestone to address this and a couple of other issues.

**Comment by eronh** [comment]
Hi, @BoruiGu 
The release 4.0.0 has been published in the marketplace :v:

**Comment by BoruiGu** [comment]
Awesome thanks! @heronsilva
