### ISSUE TITLE
Text highlighting seems wrong

### ISSUE THREAD

**Issue by alexleduc76** [firefox-theme/visual-studio-code#15]
Would it be possible to change it so that when you highlight part of a word, only the selected characters gets highlighted? This theme seems to be the only one to highlight the whole word regardless of what you select. For example in the attached screenshot, I only selected the text "UniqueID" but all of "generateUniqueID" is highlighted.
![screenshot 59](https://user-images.githubusercontent.com/13103140/59390737-22a25c80-8d40-11e9-86e7-ba87bad0cb3c.png)

Otherwise, great theme!

**Comment by eronh** [comment]
Hello, @alexleduc76 !
Thank you for reporting this issue. Also, sorry for the late reply.
I will do some work on this and release a minor update soon.

**Comment by alexleduc76** [comment]
Awesome!

**Comment by eronh** [comment]
Hi @alexleduc76 !
I fixed this just yesterday. Let me know what you think about the updated text/selection highlighting :)

Thx!

**Comment by alexleduc76** [comment]
Great, thank you!
