### ISSUE TITLE
Changed/Added files on is too bright on explorer (light theme)

### ISSUE THREAD

**Issue by ranzolinrafa** [firefox-theme/visual-studio-code#16]
Changed/Added files on is too bright on explorer (light theme)

i'm on windows. 

:) thanks

**Comment by eronh** [comment]
Hey, @ranzolinrafa :wave: 

Thank you for reporting this issue.
I will work on it in the next few days and will let you know when I finish.

Thx!

**Comment by eronh** [comment]
Hey, @ranzolinrafa :wave: 
Sorry for the delay.

I made some improvements on the git colors on the explorer. Let me know what you think.

Abraço :)
