### ISSUE TITLE
Missing link and inline code styles in Markdown Preview

### ISSUE THREAD

**Issue by metamas** [firefox-theme/visual-studio-code#18]
Link and inline code style aren't differentiated from plain text in _Firefox Dark_ when viewing a _Markdown Preview_.

A link's style is only visibly different from plain text if you hover over it. Then it matches the _Firefox Dark (Classic)_ style.

The inline code is monospace, but still difficult to spot without any other style difference.

I've looked at `dark.yml`, and it does appear that differnt text colors have not been set for these elements. I've just forked and fixed them to match the settings for Dark (Classic). I will submit a PR now.

**Light:**
![image](https://user-images.githubusercontent.com/2520253/63657087-dd43d780-c751-11e9-8341-16ab8a1b7d23.png)

**Dark**
![image](https://user-images.githubusercontent.com/2520253/63657117-62c78780-c752-11e9-8cbe-29f8d3759ab6.png)

**Dark (Classic)**
![image](https://user-images.githubusercontent.com/2520253/63657122-7246d080-c752-11e9-9b6f-2c0d69baa682.png)

**Comment by eronh** [comment]
Hi @metamas :wave: 

Thank you for creating the issue and for submitting the pull request.
The release 4.8.0 is now available.

Cheers!
