### ISSUE TITLE
Question about file structure for theme configs

### ISSUE THREAD

**Issue by metamas** [firefox-theme/visual-studio-code#20]
Hi again @heronsilva. Btw, thanks for making this theme. It's by far my favorite for VS Code :)

While I was fixing #19, I couldn't help but wonder why the configs for theme variants differed in location and file format:

**Dark:** `src/dark.yaml`
**Dark (Classic):** `themes/dark-classic.json`
**Light:** `themes/light.json`

Is this structure necessary for how VS Code interprets themes?

**Comment by eronh** [comment]
Hello @metamas. Thank you :)

It is not necessary at all. That was when I was updating to the current Firefox' colors and wanted to do something fancy. So I created a YAML file, just so I could use variables and stuff. There is also the `build.js` script that converts the `dark.yaml` file to a regular JSON.

But I plan to change that and use only JSON files soon.

Thx :v:

**Comment by metamas** [comment]
Ah, I see. Thanks for clarifying. If I get some time today (or this weekend), maybe I'll take care of it and send you a PR.

**Comment by eronh** [comment]
Thank you, but you don't have to worry about it.
I will work on that as soon as I have some free time.

Anyway, your PRs are always welcome :)
