### ISSUE TITLE
Light Theme: Text color of the selected terminal tab is too light to be clear.

### ISSUE THREAD

**Issue by RainmanVi** [firefox-theme/visual-studio-code#24]
Hi, love this theme, and thanks for the awesome work!

Here is my trouble:

![image](https://user-images.githubusercontent.com/29296023/112718421-d84a9980-8f2d-11eb-9a7d-c56aa6fada2a.png)

As you can see, the text color in the selected terminal tab is too light and hard to clearly see. 
It would be better if the color is the same as those on the drop-down menu.

**Comment by kolchurinvv** [comment]
Hey @RainmanVi!
I had the same issue. A quick workaround is to go to the `settings.json` and add
```
"workbench.colorCustomizations": {
    "dropdown.foreground": "#505253"
  }
```
to it. It'll change the color of the text in all "active" drop-down selectors. Preview attached
<img width="352" alt="Screen Shot 2021-08-08 at 08 07 35" src="https://user-images.githubusercontent.com/18503099/128619420-d0615893-b456-4172-8b4b-75ded245c88b.png">


P.S. VScode could do better with a more semantic namespace other than 'foreground' - took some digging to figure this one out.
