### ISSUE TITLE
update color pallete for Firefox DevTools version 57?

### ISSUE THREAD

**Issue by icaroramiires** [firefox-theme/visual-studio-code#5]
Is there an update for the color palette of version 57? that color scheme was cool :)

**Comment by eronh** [comment]
Hi, Icaro!

I was not aware of this new theme in FF 57. But now, I will certainly work on a new update.

Muito obrigado pelo feedback :+1:

**Comment by icaroramiires** [comment]
thanks! I'm waiting for an update. 👍
