### ISSUE TITLE
Wrong highlight for attritube

### ISSUE THREAD

**Issue by Austaras** [firefox-theme/visual-studio-code#6]
![2018-04-19](https://user-images.githubusercontent.com/15013925/38967105-18b88f5a-43b8-11e8-88d7-b81aaf1b7ecd.png)
only function is highlighted

**Comment by eronh** [comment]
Hello, @Austaras ! Thank you for taking time to report this issue.
I'll release a fix as soon as I can :v:

**Comment by eronh** [comment]
What do you think about this?
![image](https://user-images.githubusercontent.com/9641348/38968528-382ec346-4362-11e8-927c-62961ff5c50d.png)

As both properties and functions have the same colour, I added the _italic_ style to properties of type `function`.

**Comment by Austaras** [comment]
@heronsilva cool!And gladly to see string literal is highlighted in blue
hope to see a new release soon

**Comment by eronh** [comment]
All done!
Also, Fira Code for the win :tada: \o/
