### ISSUE TITLE
String templates don't have enough contrast

### ISSUE THREAD

**Issue by mariogillazaro** [firefox-theme/visual-studio-code#7]
Hi, the theme is amazing but string templates are too bright to actually read them 

![screen shot 2018-06-22 at 2 44 45 pm](https://user-images.githubusercontent.com/31219005/41796123-e3062368-762a-11e8-9f0c-1ba7202907d9.png)

**Comment by eronh** [comment]
Hi Mario!

Thanks for reporting this issue.
I will be working on it and will release an update soon :)

**Comment by eronh** [comment]
All done!

Sorry for the delay. New release 3.2.2 is now available :)
