### ISSUE TITLE
Light theme: Tab text etc. too light and not readable

### ISSUE THREAD

**Issue by rugk** [firefox-theme/visual-studio-code#8]
This is hardly readable:

![grafik](https://user-images.githubusercontent.com/11966684/42783658-effe6a14-894c-11e8-867d-af82af78d492.png)

**Comment by eronh** [comment]
Hi @rugk 
Thank you for reporting this issue.

I'll be working on it and will publish a new release within the next few days.

**Comment by rugk** [comment]
Actually I saw it's the same in the default pre-installed light themes. So it may not be your fault. 😉

**Comment by eronh** [comment]
Hi @rugk 
Sorry for the delay.
I released version 3.3.0 improving the active/inactive tab foreground. Let me know what you think ;)
