### ISSUE TITLE
Firefox light theme: yellow is too bright 

### ISSUE THREAD

**Issue by rijine** [firefox-theme/visual-studio-code#9]
![image](https://user-images.githubusercontent.com/1145401/43522766-9cf01dfe-959a-11e8-8d78-3b3b2fd64632.png)

**Comment by eronh** [comment]
Hi @rijine 
Thanks for reporting this issue.

I haven't had time to work on the theme recently, but possibly on sunday I'll publish a new release fixing both this and #8 issue

**Comment by rijine** [comment]
@heronsilva thank you.. this. is also little light color, it will be good you can take this also

![image](https://user-images.githubusercontent.com/1145401/43658242-9acfe198-9758-11e8-8107-de473636bc31.png)

**Comment by eronh** [comment]
Hi @rijine 
Sorry for the delay.
I released version 3.3.0 with small syntax improvements. Let me know what you think ;)

**Comment by eronh** [comment]
I couldn't find the issue with the yellow parenthesis. What language is that exactly?
